### ISSUE TITLE
linux无法使用

### ISSUE THREAD

**Issue by zhongguo1987** [wangpengxpy/ASP.NETCoreResumeDownload#1]
使用asp.net.core 2.1.5重新编译，发布到centos7.4系统上。功能出现异常，无法使用

**Comment by wangpengxpy** [comment]
@zhonggguo1987   出现什么异常，请提供详细异常信息？

**Comment by wangpengxpy** [comment]
https://www.cnblogs.com/CreateMyself/p/8449414.html
根据博客评论注入下呢。

**Comment by zhongguo1987** [comment]
您好，已经注入了。异常就是使用edge浏览器，下载到95%,左右，直接就崩溃了，Kestrel显示不支持数据了。换了下载工具，迅雷，然后下载中间，点击停止，下次开启，一直不动的。

**Comment by zhongguo1987** [comment]
我发布上去，Linux是用的Kestrel本身作为web服务器的，并没有配置nginx反向代理。

**Comment by wangpengxpy** [comment]
@zhonggguo1987   手头没有你这个环境，建议你在上传接口里写个日志或者直接将web.config配置的创建日志启用，这样能看到是否是抛出异常。
